CREATE DATABASE roteiro6;

USE roteiro6;

CREATE TABLE tbUsuario (
  id INT NOT NULL AUTO_INCREMENT,
  login VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  foto VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
